modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="duckylib"
version="${file.jarVersion}"
displayName="DuckyLib"
description="A modern GUI library for Forge 1.20.1 with TOML-based layouts and live in-game editor."
authors="j3ly"

[[dependencies.duckylib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.duckylib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="CLIENT"
